libc_a_SOURCES += \
	%D%/ffs.c \
	%D%/ieeefp.c \
	%D%/memccpy-asm.S \
	%D%/memccpy.c \
	%D%/memchr.c \
	%D%/memcpy-asm.S \
	%D%/memcpy.c \
	%D%/memmove-asm.S \
	%D%/memmove.c \
	%D%/memrchr.c \
	%D%/memset.S \
	%D%/setjmp.S \
	%D%/stpcpy.c \
	%D%/strcmp.S \
	%D%/strcpy.c \
	%D%/strlen.c
