libc_a_SOURCES += \
	%D%/stdc_bit_ceil.c \
	%D%/stdc_bit_floor.c \
	%D%/stdc_bit_width.c \
	%D%/stdc_count_ones.c \
	%D%/stdc_count_zeros.c \
	%D%/stdc_first_leading_one.c \
	%D%/stdc_first_leading_zero.c \
	%D%/stdc_first_trailing_one.c \
	%D%/stdc_first_trailing_zero.c \
	%D%/stdc_has_single_bit.c \
	%D%/stdc_leading_ones.c \
	%D%/stdc_leading_zeros.c \
	%D%/stdc_trailing_ones.c \
	%D%/stdc_trailing_zeros.c
